In [1]:
import pandas as pd
import os
import matplotlib.pyplot as ply
%matplotlib inline

In [ ]:
from dotenv import load_dotenv
import os
load_dotenv()
os.environ["OPENROUTER_API_KEY_LEDE"][:8]

In [3]:
df_1 = pd.read_csv('202601_CPGF.csv', encoding="latin1", sep=";")
df_1

,CÓDIGO ÓRGÃO SUPERIOR,NOME ÓRGÃO SUPERIOR,CÓDIGO ÓRGÃO,NOME ÓRGÃO,CÓDIGO UNIDADE GESTORA,NOME UNIDADE GESTORA,ANO EXTRATO,MÊS EXTRATO,CPF PORTADOR,NOME PORTADOR,CNPJ OU CPF FAVORECIDO,NOME FAVORECIDO,TRANSAÇÃO,DATA TRANSAÇÃO,VALOR TRANSAÇÃO
0,63000,Advocacia-Geral da União,63000,Advocacia-Geral da União - Unidades com víncul...,110161,SUPERINTENDENCIA REG. DE ADMIN. DA 1ª REGIAO,2026,1,***.195.852-**,JOSE UELISSON ALVES LEITE,43594727000157,VINIL DECOR MOLDURARIA DECORACAO E COMERICO LTDA,COMPRA A/V - R$ - APRES,05/12/2025,"91,86"
1,63000,Advocacia-Geral da União,63000,Advocacia-Geral da União - Unidades com víncul...,110161,SUPERINTENDENCIA REG. DE ADMIN. DA 1ª REGIAO,2026,1,***.212.021-**,SYLVIO EDGARD DE CASTRO,72649361000174,HBL CARIMBOS E PLACAS INDUSTRIA E COMERCIO LTDA,COMPRA A/V - R$ - APRES,19/12/2025,"1435,20"
2,63000,Advocacia-Geral da União,63000,Advocacia-Geral da União - Unidades com víncul...,110161,SUPERINTENDENCIA REG. DE ADMIN. DA 1ª REGIAO,2026,1,***.195.852-**,JOSE UELISSON ALVES LEITE,5705694000186,J D COMERCIO E IMPORTACAO LTDA,COMPRA A/V - R$ - APRES,05/12/2025,"336,70"
3,63000,Advocacia-Geral da União,63000,Advocacia-Geral da União - Unidades com víncul...,110161,SUPERINTENDENCIA REG. DE ADMIN. DA 1ª REGIAO,2026,1,***.562.861-**,ANTONIO CARLOS MELO DOS SANTOS,55159876000177,AUDIOPRO COMERCIO DE PRODUTOS DE AUDIO E VIDEO...,COMPRA A/V - R$ - APRES,19/12/2025,"312,00"
4,63000,Advocacia-Geral da União,63000,Advocacia-Geral da União - Unidades com víncul...,110161,SUPERINTENDENCIA REG. DE ADMIN. DA 1ª REGIAO,2026,1,***.562.861-**,ANTONIO CARLOS MELO DOS SANTOS,55159876000177,AUDIOPRO COMERCIO DE PRODUTOS DE AUDIO E VIDEO...,COMPRA A/V - R$ - APRES,16/12/2025,"805,00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9674,20000,Presidência da República,20101,Presidência da República,110001,SECRETARIA DE ADMINISTRACAO/PR,2026,1,***.074.148-**,ROGERIO DO NASCIMENTO,6239994000180,AUTO POSTO PARQUE VILLA LOBOS LTDA.,COMPRA A/V - R$ - APRES,04/12/2025,"259,84"
9675,20000,Presidência da República,20101,Presidência da República,110001,SECRETARIA DE ADMINISTRACAO/PR,2026,1,***.074.148-**,ROGERIO DO NASCIMENTO,6239994000180,AUTO POSTO PARQUE VILLA LOBOS LTDA.,COMPRA A/V - R$ - APRES,28/11/2025,"168,31"
9676,20000,Presidência da República,20101,Presidência da República,110001,SECRETARIA DE ADMINISTRACAO/PR,2026,1,***.074.148-**,ROGERIO DO NASCIMENTO,6239994000180,AUTO POSTO PARQUE VILLA LOBOS LTDA.,COMPRA A/V - R$ - APRES,19/12/2025,"187,76"
9677,20000,Presidência da República,20101,Presidência da República,110001,SECRETARIA DE ADMINISTRACAO/PR,2026,1,***.074.148-**,ROGERIO DO NASCIMENTO,6239994000180,AUTO POSTO PARQUE VILLA LOBOS LTDA.,COMPRA A/V - R$ - APRES,23/12/2025,"172,16"
9678,20000,Presidência da República,20101,Presidência da República,110001,SECRETARIA DE ADMINISTRACAO/PR,2026,1,***.383.038-**,ROBERTO BUENO FONTANA,60570793000106,AUTO POSTO HYGIENOPOLIS LTDA,COMPRA A/V - R$ - APRES,11/12/2025,"180,03"

In [26]:
data = pd.read_json('response_1784663652354.json', encoding="latin1")

In [29]:
import json

with open('response_1784664659228.json', encoding='latin1') as f:
    data = json.load(f)

df = pd.json_normalize(data)
df

,id,mesExtrato,dataTransacao,valorTransacao,tipoCartao.id,tipoCartao.codigo,tipoCartao.descricao,estabelecimento.id,estabelecimento.cpfFormatado,estabelecimento.cnpjFormatado,...,unidadeGestora.orgaoVinculado.codigoSIAFI,unidadeGestora.orgaoVinculado.cnpj,unidadeGestora.orgaoVinculado.sigla,unidadeGestora.orgaoVinculado.nome,unidadeGestora.orgaoMaximo.codigo,unidadeGestora.orgaoMaximo.sigla,unidadeGestora.orgaoMaximo.nome,portador.cpfFormatado,portador.nis,portador.nome
0,474900093,07/2025,17/06/2025,"447,93",1,1,CartÃ£o de Pagamento do Governo Federal - CPGF,556016978,,33.209.512/0001-11,...,26433,10952708000104,IFRJ,"Instituto Federal de EducaÃ§Ã£o, CiÃªncia e Te...",26000,MEC,MinistÃ©rio da EducaÃ§Ã£o,***.122.497-**,,DANIEL DIAS LEONARDO MARTINS
1,474900157,07/2025,18/06/2025,"235,50",1,1,CartÃ£o de Pagamento do Governo Federal - CPGF,607889130,,60.090.163/0001-34,...,26433,10952708000104,IFRJ,"Instituto Federal de EducaÃ§Ã£o, CiÃªncia e Te...",26000,MEC,MinistÃ©rio da EducaÃ§Ã£o,***.122.497-**,,DANIEL DIAS LEONARDO MARTINS
2,474900221,07/2025,25/06/2025,"510,00",1,1,CartÃ£o de Pagamento do Governo Federal - CPGF,1919011,,14.479.778/0001-30,...,22202,00348003000110,EMBRAPA,Empresa Brasileira de Pesquisa AgropecuÃ¡ria,22000,MAPA,MinistÃ©rio da Agricultura e PecuÃ¡ria,***.588.328-**,,LUIZ VICENTE PEREIRA
3,474900285,07/2025,24/06/2025,"686,00",1,1,CartÃ£o de Pagamento do Governo Federal - CPGF,4918635,,14.574.032/0001-05,...,22202,00348003000110,EMBRAPA,Empresa Brasileira de Pesquisa AgropecuÃ¡ria,22000,MAPA,MinistÃ©rio da Agricultura e PecuÃ¡ria,***.382.302-**,,BENEDITO PONTES SILVA
4,474900349,07/2025,24/06/2025,"425,00",1,1,CartÃ£o de Pagamento do Governo Federal - CPGF,479018024,,07.486.620/0002-02,...,22202,00348003000110,EMBRAPA,Empresa Brasileira de Pesquisa AgropecuÃ¡ria,22000,MAPA,MinistÃ©rio da Agricultura e PecuÃ¡ria,***.382.302-**,,BENEDITO PONTES SILVA
5,474900413,07/2025,06/06/2025,"940,00",1,1,CartÃ£o de Pagamento do Governo Federal - CPGF,212174006,,33.650.301/0001-10,...,36211,26989350000116,FNS,FundaÃ§Ã£o Nacional de SaÃºde,36000,SAÃDE,MinistÃ©rio da SaÃºde,***.154.791-**,,FABIO SANTANA DE OLIVEIRA
6,474900477,07/2025,06/06/2025,"80,00",1,1,CartÃ£o de Pagamento do Governo Federal - CPGF,276654500,,30.260.679/0001-19,...,36211,26989350000116,FNS,FundaÃ§Ã£o Nacional de SaÃºde,36000,SAÃDE,MinistÃ©rio da SaÃºde,***.154.791-**,,FABIO SANTANA DE OLIVEIRA
7,474900541,07/2025,06/06/2025,"1.600,00",1,1,CartÃ£o de Pagamento do Governo Federal - CPGF,607870968,,14.428.894/0001-20,...,36211,26989350000116,FNS,FundaÃ§Ã£o Nacional de SaÃºde,36000,SAÃDE,MinistÃ©rio da SaÃºde,***.154.791-**,,FABIO SANTANA DE OLIVEIRA
8,474900605,07/2025,09/06/2025,"2.370,00",1,1,CartÃ£o de Pagamento do Governo Federal - CPGF,603218167,,26.411.220/0001-00,...,36211,26989350000116,FNS,FundaÃ§Ã£o Nacional de SaÃºde,36000,SAÃDE,MinistÃ©rio da SaÃºde,***.667.451-**,,DORCENI DE JESUS GOMES MAIA
9,474900669,07/2025,09/06/2025,"290,22",1,1,CartÃ£o de Pagamento do Governo Federal - CPGF,29793295,,04.699.455/0001-06,...,52904,00394452054700,FUNDO DO EXÃRCITO,Fundo do ExÃ©rcito,52000,DEFESA,MinistÃ©rio da Defesa,***.876.787-**,,PAULO GUSTAVO DA SILVA MARINS
10,474900733,07/2025,09/06/2025,"43,43",1,1,CartÃ£o de Pagamento do Governo Federal - CPGF,29793295,,04.699.455/0001-06,...,52904,00394452054700,FUNDO DO EXÃRCITO,Fundo do ExÃ©rcito,52000,DEFESA,MinistÃ©rio da Defesa,***.876.787-**,,PAULO GUSTAVO DA SILVA MARINS
11,474900797,07/2025,13/06/2025,"316,41",1,1,CartÃ£o de Pagamento do Governo Federal - CPGF,169617603,,14.137.177/0001-49,...,52904,00394452054700,FUNDO DO EXÃRCITO,Fundo do ExÃ©rcito,52000,DEFESA,MinistÃ©rio da Defesa,***.876.787-**,,PAULO GUSTAVO DA SILVA MARINS
12,474900861,07/2025,13/06/2025,"67,56",1,1,CartÃ£o de Pagamento do Governo Federal - CPGF,353818523,,03.743.710/0001-08,...,52904,00394452054700,FUNDO DO EXÃRCITO,Fundo do ExÃ©rcito,52000,DEFESA,MinistÃ©rio da Defesa,***.876.787-**,,PAULO GUSTAVO DA SILVA MARINS
13,474900925,07/2025,27/05/2025,"70,00",1,1,CartÃ£o de Pagamento do Governo Federal - CPGF,-2,,,...,46000,00489828000155,MGI,MinistÃ©rio da GestÃ£o e da InovaÃ§Ã£o em Serv...,46000,MGI,MinistÃ©rio da GestÃ£o e da InovaÃ§Ã£o em Serv...,***.444.170-**,,DANIELA MAZZUCO DE SOUZA PRADO
14,474900989,08/2025,10/07/2025,"300,00",1,1,CartÃ£o de Pagamento do Governo Federal - CPGF,819685,,31.304.371/0001-90,...,52131,00394502000144,CMDO MARINHA,Comando da Marinha,52000,DEFESA,MinistÃ©rio da Defesa,***.513.827-**,,ROBSON DA SILVA LIMA BARROS

In [ ]:
#só retornou a primeira página
#então, vale a pena fazer o pedido no pelo python
#refazer o pedido